api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    title: 'API Symfony'
    description: 'API Rest realizada en Symfony 4.4 (LTS) para gestión de productos y categorías'
    version: '1.0.0'
    collection:
        pagination:
            enabled: false
